---
- name: Install k3s service
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable k3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes
