---
- name: Test for cmdline.txt
  stat:
    path: /boot/firmware/cmdline.txt
  register: cmdline

- name: Activating cgroup on cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*fixrtc)$'
    line: '\1 cgroup_enable=memory'
    backrefs: true
  when: ( cmdline.stat.path is defined )
          and
        ( ansible_facts.architecture is search("arm") )
  register: boot_cmdline
  notify:
    - reboot raspberry pi
